# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  host: http://www.firewallsolution.mn/
  meta_title: firewall solution
  meta_description: firewall solution
  meta_keywords: firewall solution
  pager: 10

  phone: 99052507, 99031556, 99993979
  email: martino_ikhee@yahoo.com
  address: Баянзүрх дүүрэг
  address_en: Bayanzurkh district
  order_email: info@firewallsolution.mn
  facebook: FirewallSolution
  twitter: FirewallSolution
  youtube: channel/UClyKDuRYYdBjzdZxEiKfLag
  skype: FirewallSolution
  yahoo: FirewallSolution
  lat: 47.9029
  lng: 107.029
  invoice_email: info@firewallsolution.mn