# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        FIREWALL SOLUTION | ADMIN PANEL
    description:  firewall solution
    keywords:     firewall solution
    language:     en
    robots:       index, follow

  stylesheets:    [admin/back.css, admin/backBlue.css, admin/backForm.css]

  javascripts:    []

  has_layout:     true
  layout:         layout