# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  host: http://localhost:88/firewall/web/
  #host: http://firewall/
  meta_title: firewall solution
  meta_description: firewall solution
  meta_keywords: firewall solution
  pager: 10

  phone: (+976) 99026025 &nbsp; , (+976) 99258807
  email: firewallsolution.llc@gmail.com
  address: Баянзүрх дүүрэг, 14-р хороо, Самбуугийн гудамж - Jobi 72 төв. Жуковын талбайгаас баруун тийш 100 метр.
  address_en: Bayanzurkh district
  order_email: firewallsolution.llc@gmail.com
  facebook: FirewallSolution
  twitter: FirewallSolution
  youtube: channel/UClyKDuRYYdBjzdZxEiKfLag
  skype: FirewallSolution
  yahoo: FirewallSolution
  lat: 47.9029
  lng: 107.029
  invoice_email: firewallsolution.llc@gmail.com